### ISSUE TITLE
Governance process to add new repositories

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/meta#1]
Hi Maintainers, we really need to decide in which way new repositories should be added to the ecosystem. My proposal:

The team making this decision should be composed by all repo maintainers inside the ecosystem (5 at the moment, 6 soon), but i would keep a veto right as steward of the project (to be used only in extreme cases).

Proposals to add and remove a new repository should be posted here on meta using the issue tracker (and the label `repo proposal`). A repository will be accepted once at least 50%+1 of the maintainers specifically approve. To approve a new repository maintainers should comment with `ACK` ("Acknowledged"), to disapprove: `NACK` (Not Acknowledged).

I added all repo maintainers in the @monero-ecosystem/maintainers team, so that when a feedback is needed we can just ping that team.

Thoughts?

**Comment by lh1008** [comment]
It's good to know that there should be a governance inside the repository. Some community members were asking what happens if someone goes rogue inside the Monero ecosystem? I will be posting a proposal to add a new repository soon. :)

**Comment by erciccione** [comment]
pinging @monero-ecosystem/maintainers for discussion

**Comment by lh1008** [comment]
I'm here :) :+1:

**Comment by NoThisIsPatrik** [comment]
I'm here. I need to remember to update the repo at some point btw, adjusted
it to work in python 3. But also half-way added SHUFFLE/INT_MATH functions,
which I believe is supposed to be in next hardfork at some point. And
didn't properly use git. But that's a whole different thing, I'm just
typing it out loud on the basis that if I admit to actually needing to,
perhaps I'll get around to it.

**Comment by Lafudoci** [comment]
> accepted once at least 50%+1 of the maintainers specifically approve.

Sounds good to me, but what criteria should we use to approve it? Monero related or useful? I believe we should encouge the diversity of this ecosystem. So maybe related is enough?

**Comment by erciccione** [comment]
Now that we have the attention of all maintainers i'll write down point for point my proposal of governance for this repo:

+ The team who decide which proposals should be included and which not is composed by all repo maintainers inside the ecosystem. I will keep a veto right as steward of the project (to be used only in extreme cases).
+ Proposals to add and remove a new repository should be posted here on meta using the issue tracker
+ A repository will be accepted/removed when 50%+1 of the maintainers partecipating to the discussion reach consensus
+ Substantial decision about the Monero Ecosystem project shall be make using the same system as for the precedent point 
+ Mainteiners shall declare their intention of vote using: the 'thumb up' (+1) or 'thumb down' (-1) buttons on github; commenting with `ACK` (Acknowledged) or `NACK` (Not Acknowledged)

I think this is an essential and fair governance program, but if something is not clear enough or somebody think it needs to be modified, please comment. Once we reach consensus i will add it on the readme here on meta. Obviously, it can always be modified with a Pull Request, using our governance system.

> Sounds good to me, but what criteria should we use to approve it? Monero related or useful?

@Lafudoci We should use both criterial. The repository must be Monero related, but also useful and complex enough. I would prefer less repo, but higher quality

**Comment by erciccione** [comment]
@NoThisIsPatrik thanks for the updated, let us know if you need any help/support :)

**Comment by Lafudoci** [comment]
> The repository must be Monero related, but also useful and complex enough. I would prefer less repo, but higher quality

@erciccione Good point, got it.

**Comment by erciccione** [comment]
Governance system added to readme with #18
