### ISSUE TITLE
Add python-monerorpc to monero ecosystem

### ISSUE THREAD

**Issue by normoes** [monero-ecosystem/meta#11]
Hi,

I have created [python-monerorpc](https://github.com/XMRto/python-monerorpc).

It is a fork of [python-bitcoinrpc](https://github.com/jgarzik/python-bitcoinrpc) and was adapted to be used wirth **monero daemon rpc** and the **monero wallet rpc**.

Example:

```
rpc_connection = AuthServiceProxy('http://{0}:{1}@127.0.0.1:18081'.format(rpc_user, rpc_password))
info = rpc_connection.get_info()
```

Maybe you could have a look at it and add it to the monero-ecosystem eventually.

That would be great.
Have a nice day.

**Comment by skftn** [comment]
@normoes Heya. Could you elaborate on the differences between your module and https://github.com/emesik/monero-python ? Thanks!

**Comment by normoes** [comment]
`monero-python` can do way more than my simple module. It also includes some utilities as a monero address validator for instance. 

As far as I understand, it is the complete suite.

`python-monerorpc` is just the part that communicates with the `daemon via rpc` or with `monero-wallet-rpc`. What makes it interesting is that it is highly dynamic So when devloping, you just use RPC methods as class/object properties of the `AuthServiceProxy` and they are "converted" to HTTP calls to the RPC backend. That's what `python-bitcoinrpc` also does and I like the appraoch very much.
`python-monerorpc` uses `requests.Session` which keeps the HTTP connection alive and resues it.
`python-monerorpc` handles calls to the `daemon rpc` and `monero-wallet-rpc` using the exact same functionality - The only difference is the intitial configuration.

I just saw that `monero-python` uses a backend called `jsonrpc.py`. Essentially that's what `python-monerorpc` could replace as a module.

**Comment by normoes** [comment]
I had a closer look at `monero-python`.

`python-monerorpc` and `monero-python` are more similar than I thought initially. In fact, `monero-python` implements a backend that communicates with monero using RPC. It is thoroughly implemented as python class with methods and the module implements classes around this backend to make its use more comfortable.
`python-monerorpc` is just a very dynamic backend - It could still replace `monero-python`'s backend.

A practical difference:

Should a RPC method change or a new one should be added, `monero-python` would have to adapt its backend and the implementations around it, while with `python-monerorpc`  you just have to modify the propert or use a new method like:

* `rpc_connection.getbalance()` -> `rpc_connection.get_balance()`
* `rpc_connection.new_method()`

**Comment by Lafudoci** [comment]
@erciccione  @normoes Sorry for late response, I just tried and found some issues.
- It seems `setuptools `should be use intead of `distutils`, or `install_requires` won't work.
And `open('README').read()` give an exception here because should be pointed to `README.md`.
https://github.com/XMRto/python-monerorpc/blob/84cfee6080a62cd32e8f0478f63a1002c4c20579/setup.py#L3-L18
- `python setup.py` needs arg, I tried `python setup.py install --user` and it works for me.
https://github.com/XMRto/python-monerorpc/blob/84cfee6080a62cd32e8f0478f63a1002c4c20579/README.md#L50
- This module is not compatible with python3.x . It's a drawback for long-term project since python2.x is stepping down. I suggest at least put it in the roadmap.

Overall I'll ACK this project after the issues above are addressed. It could be useful backend of many Monero projects.

**Comment by normoes** [comment]
Nice!
Thanks for the reply.

I'll address them and come back to you.

**Comment by normoes** [comment]
@Lafudoci Would you mind testing it again, pelase.

* I adapted the `README.md`.
* I pointed to `README.md` in `setup.py`.
* pyhon3 should work.
* `setuptools` replaced `distutils.core`

**Comment by Lafudoci** [comment]
@normoes Nice work, can confirm installation issue was resolved and works with python3, ACK.

**Comment by erciccione** [comment]
Good, we have consensus. Thanks @Lafudoci and @skftn for the reviews.

@normoes ping me when you are ready, so we can start the migration. Can you also provide a one line descriction of the repo?

**Comment by normoes** [comment]
Some minor adaptions to the `batch_()` function and then we are ready to go.

Thanks for all the support.

**Comment by normoes** [comment]
@erciccione Ready for migration.

One line description (taken form the README):
python-monerorpc is an improved version of python-jsonrpc for Monero (monerod rpc, monero-wallet-rpc).

**Comment by erciccione** [comment]
@normoes I sent you the invitation, please accept and transfer the repo :)

**Comment by normoes** [comment]
Thanks :)

**Comment by erciccione** [comment]
There it is: https://github.com/monero-ecosystem/python-monerorpc
Migration is completed. Closing this issue. Thanks everybody
