### ISSUE TITLE
Consider adding icryptonode repo

### ISSUE THREAD

**Issue by Gingeropolous** [monero-ecosystem/meta#12]
Repo proposal

https://github.com/seibelj/iCryptoNode

i have an attachment to this, as that whole thing is what my original monerodo OS was supposed to do. It turns out I just suck at coding. This cryptonode guy doesn't seem to suck.

**Comment by erciccione** [comment]
Thanks @Gingeropolous, will open an issue on @seibelj's repo and ask for his imput

**Comment by lh1008** [comment]
Looks nice.

**Comment by erciccione** [comment]
Never got an answer. Closing
