### ISSUE TITLE
Remove 'monero-docs'

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/meta#16]
I created the [monero-docs](https://github.com/monero-ecosystem/monero-docs) repository in the ecosystem time ago, but it was never used. If it's ok for the maintainers, I think it should be remove it. This for the policy "No dead repos in the ecosystem". (A thumbs up or down is more than enough here, don't think much discussion is needed)

@monero-ecosystem/maintainers

**Comment by normoes** [comment]
For me that's OK, since it is outdated as you said.

Is there any information which should be transferred to somewhere else?

**Comment by erciccione** [comment]
@normoes No. The repo was born empy and will probably die empty :)

**Comment by lh1008** [comment]
Yes you can remove it.

**Comment by erciccione** [comment]
Removed from list (#17 ) and from the ecosystem
