### ISSUE TITLE
Add Pymonero repository

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/meta#19]
I proposed @ehanoc to add **[Pymonero](https://github.com/ehanoc/pymonero)** to the Monero Ecosystem and he agreed. See [monero-project/monero#4996 (comment)](https://github.com/monero-project/monero/issues/4996#issuecomment-448611219).

Pymonero is a fork of monero-project/monero to deliver python c++ bindings, maybe @ehanoc can tell us more about the project and its goals.

pinging @monero-ecosystem/maintainers as per our governance system. Please express your opinion.

**Comment by erciccione** [comment]
@ehanoc To be clear, the monero ecosystem only hosts projects which will be maintained and kept updated. I see the project is not updated since the end of May. Do you plan to keeping this repo constantly updated?

**Comment by ehanoc** [comment]
@erciccione I do want to keep it updated as much as possible. I have found some interest within my current Organization too (see profile). But just by myself would be hard i must say...

I started this as a need for myself initially; as i didn't want to use re-written implementations and wrappers. With bindings you don't need those, you can re-use the core codebase and it's easy to integrate new features by merging the main tree and expose it with python modules.

**Comment by xmrdsc** [comment]
Cool project :+1:

**Comment by johnalanwoods** [comment]
Good idea in my view! Happy to contribute!

**Comment by erciccione** [comment]
@ehanoc Ok got it. hopefully, it will get more exposure here and we can find more contributors willing to help with maintainance/development.

+1 for me

**Comment by lh1008** [comment]
Not sure what the code says, but I would like to see more Monero independent projects working to enforce Monero. :) :+1:

**Comment by sproj** [comment]
Up for contributing. Work with ehanoc, so can get in the loop that way. While working hard, of course.

**Comment by erciccione** [comment]
@ehanoc consensus seems clear and looks like we also found some volunteers willing to contribute to the project, great! Now we only have to transfer the repo. Ping me when you are ready please

**Comment by erciccione** [comment]
ping @ehanoc

**Comment by ehanoc** [comment]
@erciccione let's do it.

**Comment by ehanoc** [comment]
It says i don't have permissions to do so

**Comment by erciccione** [comment]
Sorry @ehanoc , now you can

**Comment by ehanoc** [comment]
done

**Comment by erciccione** [comment]
Perfect, thanks. I'm gonna add it to the README and announce it on reddit

**Comment by ehanoc** [comment]
Cool. Thanks. As a next step, we should protect the master branch.

**Comment by erciccione** [comment]
It's still your repo and you have all admin permission as before. You can do whatever you think is best :)

**Comment by erciccione** [comment]
Migration is complete (#22) and the transfer has been announced on reddit: https://www.reddit.com/r/Monero/comments/adiagu/new_member_of_the_monero_ecosystem_project/

@ehanoc Now you have right to vote as for our governance system.

Closing.
