### ISSUE TITLE
Create a github page for the ecosystem

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/meta#21]
What do you guys think about creating a simple github page for the Monero Ecosystem project? 
Every maintainer could have their own section when they can write info about their repository (even just showing the readme would be ok). I would use it a lot for the guide of the GUI, since i could have it online in an html page.
For more info about github page: https://pages.github.com/

@monero-ecosystem/maintainers

**Comment by erciccione** [comment]
I hope i will be able to set up a simple github page soon. In the meantime, if somebody feels inspired, feel free to start :)

**Comment by erciccione** [comment]
I won't be able to work on a github page in the near future, i'm really too busy for that. If soembody feel like it, would be really great to have even just a minimal website with the list of the repositories and the readme as landing page.

**Comment by Lafudoci** [comment]
@erciccione, what about this one?
I don't have much experience of making webpage. But I found there are [some pretty theme template](https://github.com/willianjusten/cards-jekyll-template) we could use. So I spent some time to build this demo page. Seems feasible to me. If you like it, I'll try to finish it.
![demo](https://user-images.githubusercontent.com/10460270/56641474-07a05e00-66a8-11e9-8f64-3e162a39c023.PNG)

**Comment by erciccione** [comment]
That looks simple and very cool! I like it, if you could work on it would be awesome @Lafudoci :)

**Comment by lh1008** [comment]
Looks good :).

**Comment by Lafudoci** [comment]
@erciccione OK, I'll work on it. First, we need to create a new repo "monero-ecosystem.github.io" for github page to work. But I don't have enough permission for creating repo. Could you do it for me and allow me to upload files to that repo? Thanks.

**Comment by erciccione** [comment]
@Lafudoci I created [monero-ecosystem/monero-ecosystem.github.io](https://github.com/monero-ecosystem/monero-ecosystem.github.io) (virgin repo) and added you as admin there :).

**Comment by Lafudoci** [comment]
Page pushed! @erciccione 

https://monero-ecosystem.github.io/

Some thing have been done:
- Clean template
- Customize layout for Monero Ecosystem projects
- Make all repo's readme into project markdown posts
- Picked some hightlight image for project post
- Add repo maintainer attribute in each project posts

To be done:
- Make a readme to document how to add/edit project posts

ps. All project posts are in the `_post/yyy-mm-dd-title.md` and they're markdown compatible. So they are quite easy to create and maintain. I didn't find a way to link post with existing md. So I manually copy/paste all the repo's info into project posts md. I hope I wont never need to do that again lol.

**Comment by erciccione** [comment]
Awesome, thanks @Lafudoci, that looks very cool. :) At this point we have a lot of cool stuf happening all at the same time. I will push the edited reame today and suggest a couple of changes to the website, then we can announce it!

**Comment by lh1008** [comment]
This looks great, amazing :)! Thanks @Lafudoci.

**Comment by erciccione** [comment]
Got the domain :)
[moneroecosystem.org](http://moneroecosystem.org)

**Comment by Lafudoci** [comment]
@erciccione I have set the CNAME. So point the domain to 185.199.108.153 then it should work.

**Comment by erciccione** [comment]
The website is online :)
