### ISSUE TITLE
Add Monerobox to the ecosystem

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/meta#23]
@Jasonhcwong asked [on reddit](https://www.reddit.com/r/Monero/comments/adiagu/new_member_of_the_monero_ecosystem_project/edi2ewu/) to add his reository to the ecosystem: **[MoneroBox](https://github.com/Jasonhcwong/monerobox)**

From the readme:
*MoneroBox aims to make a plug-and-play, zero-configuration Monero full node running on a Single-Board-Computer such as Rock64 and Raspberry Pi 3*

Waiting for the author to write on this thread some more info about the project.
Opinions? Questions?

@monero-ecosystem/maintainers 

edit: added correct link to reddit comment

**Comment by Jasonhcwong** [comment]
It is developed for Rock64 and intended to be used as a remote node for mobile wallets.  
It has a web UI and zero-conf network so that users can easily manage the box.

**Comment by Lafudoci** [comment]
It looks nice, @Jasonhcwong could you elaborate how does the "auto update" work?

**Comment by Jasonhcwong** [comment]
monero cli tools are downloaded from getmonero.org and packaged into a deb package and put to a APT repo, monerobox is configured with unattended upgrade which will check the repo and install if new version is found.  
Web UI update is done in the same way.

**Comment by erciccione** [comment]
I would like to see this repo added.

Anybody else from @monero-ecosystem/maintainers have comments?

**Comment by Jasonhcwong** [comment]
> > monerobox is configured with unattended upgrade which will check the repo and install if new version is found.
> 
> This sounds good. Good initiatives to make it more user-friendly.
> 
> @Jasonhcwong not sure if this could be answered but are the downloads GPG key verifyable before the downloading? (not sure if this can even be made or there's no problem with it)

I think all the deb packages from an APT repo are signed by the key of the repo and verified before download(when you run "apt update" to see if there is any new packages").   
  
When installing the base image, the public key of the repo is added before adding the repo.

**Comment by Jasonhcwong** [comment]
> ACK. But some minor things to suggest.
> 
> @Jasonhcwong The user manual is nicely detailed. You should put a link in README.md. Moreover, I'd like to suggest describing more about how to run Menerobox if user starts from a stock OS (rpi or Rock64). It seems the manual is designed for a pre-loaded OS? There no steps between hardware setup and using web-ui. It might make confusing.

Thanks for your suggestion, I will update the docs.

**Comment by erciccione** [comment]
@Jasonhcwong I invited you to the team, now you can accept and transfer the repo

**Comment by erciccione** [comment]
Repo is transferred, PMd (#26 ) and announced on reddit: https://www.reddit.com/r/Monero/comments/alrmbn/2_new_projects_joined_the_monero_ecosystem/. Closing this PR, thanks everybody :)
