### ISSUE TITLE
Add monero-javascript to the Ecosystem

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/meta#24]
**[Monero-Javascript](https://github.com/woodser/monero-javascript)** was recently [announced on reddit](https://www.reddit.com/r/Monero/comments/agmi6n/new_javascript_library_for_monero_released/) by @woodser. He already maintain one repository on the Ecosystem and i proposed him to add also Monero-Javascript. He agreed.

From the Readme:

_This project provides a modern JavaScript API for a Monero wallet and daemon._

_The API currently relies on running instances of [Monero Wallet RPC](https://getmonero.org/resources/developer-guides/wallet-rpc.html) and [Monero Daemon RPC](https://getmonero.org/resources/developer-guides/daemon-rpc.html).  Primary goals of this project are to support a local wallet with client-side crypto and a MyMonero wallet which shares the view key with a 3rd party to scan the blockchain._

_Main Features_

- _General-purpose library with focus on ease-of-use_
- _Clear object-oriented models to formalize Monero types and their relationships to each other_
- _Powerful API to query transactions, transfers, and vouts by their attributes_
- _Extensive test suite (110+ passing tests)_
- _Fetch and process binary data from the daemon in JavaScript using client-side crypto_

I think this is a very cool and high quality project and would be great to have it in the Ecosystem.
Thoughts? @monero-ecosystem/maintainers

**Comment by erciccione** [comment]
I personally think this is a high quality project and from the announcement on reddit seems like the code is also very well written. So, +1 for me.

**Comment by ehanoc** [comment]
+1 Javascript support is big

**Comment by Lafudoci** [comment]
+1, very great work.

**Comment by normoes** [comment]
+1

**Comment by erciccione** [comment]
@woodser Approved. Contact me to organize the transfer

**Comment by woodser** [comment]
@erciccione Ready when you are.

**Comment by woodser** [comment]
Ping @erciccione

**Comment by erciccione** [comment]
Sorry i missed the first ping somehow. You can transfer the repo anytime, post here when done please

**Comment by erciccione** [comment]
Repo is transferred, PMd (#26 ) and announced on reddit: https://www.reddit.com/r/Monero/comments/alrmbn/2_new_projects_joined_the_monero_ecosystem/. Closing this PR, thanks everybody :)
