### ISSUE TITLE
Add monero-python to the Ecosystem

### ISSUE THREAD

**Issue by emesik** [monero-ecosystem/meta#25]
Hi,

As the main author, I'd like to move the repository of [monero-python](https://github.com/emesik/monero-python) to the Ecosystem. It's version 0.5, a functional beta, which already allows to perform all base operations on a wallet:

* check balances,
* query for incoming and outgoing payments,
* send transfers,
* process mnemonic seeds,
* generate subaddresses offline,
* do address validation and integrate payment IDs,
* do some less important but nice stuff.

However, due to tight schedule and limited net access in the coming weeks (or months), I'd like to make sure all automatic stuff moves also, without too much configuration hassle. In particular I mean Travis CI and Readthedocs. Has someone dealt with those and can outline the transition?

**Comment by Lafudoci** [comment]
ACK, it's a great and active project funded by Monero FFS. @erciccione might able to help with the transition.

**Comment by erciccione** [comment]
Nice. Thanks for proposing this project @emesik . +1 from me.

About the migration, Travis is already activated since i used it for monero-GUI-guide. It will just be enough for me to thick a box and you will have travis immediatly working as it did before, only difference will be the different page for the bots.
I'm not familiar with Readthedocs. How does the implementation work? is there some kind of Oauth that can be enabled on GitHub?

**Comment by erciccione** [comment]
Forgot to ping: @monero-ecosystem/maintainers

**Comment by lh1008** [comment]
Sounds interesting :) :+1:

**Comment by normoes** [comment]
I am all for it. It seems to be a good library to get the complete set of functionalities.

You should consider to integrate [`python-monerorpc`](https://github.com/monero-ecosystem/python-monerorpc) as your RPC backend.

**Comment by xmrdsc** [comment]
+1

**Comment by erciccione** [comment]
@emesik contact me so we can organize the transfer :)

**Comment by emesik** [comment]
@erciccione let's do it. I can't find any address to contact you directly. Shall I just initiate _Transfer ownership_ action?

**Comment by erciccione** [comment]
Great. Yes, you can just transfer ownership to monero-ecosystem.

FYI: a list of ways to directly contact me: https://github.com/monero-ecosystem/monero-translations#contacts

**Comment by erciccione** [comment]
[Announced on GitHub](https://www.reddit.com/r/Monero/comments/b3s0eb/monero_python_a_comprehensive_python_module_for/) and opened #28 .

The migration is complete.
