### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/meta#27]
That's it, we need one. If somebody can make it or have ideas, please comment.

**Comment by Mansarde** [comment]
Maybe an umbrella with the Monero "M" on it, because: it _gathers_ multiple different things under itself.
Like an "umbrella corporation" or an "umbrella term", etc.
In this case the "things" would be the different projects/repositories.

The umbrella could be shown either from the side or from the top.

**Comment by Jasonhcwong** [comment]
I though the  "monero heart" badge on github  is our logo?

**Comment by erciccione** [comment]
Thanks for the ideas @Mansarde , hopefully somebody will create some samples.

@Jasonhcwong the 'Monero Heart' is just a placeholde, i took it from themonera.art, but would be nice to have an actual personalized logo.

**Comment by lh1008** [comment]
![monero-ecosystem](https://user-images.githubusercontent.com/7443480/53856265-3bf87780-3f9f-11e9-9b38-0f1dc178d349.png)

**Comment by erciccione** [comment]
Posted on reddit: https://www.reddit.com/r/Monero/comments/bai6pi/the_monero_ecosystem_project_needs_a_logo/

**Comment by xmrdsc** [comment]
It's not a logo but here is a bird

![](https://i.redd.it/bjyh62ncxtp21.jpg)

Hope it helps.

**Comment by erciccione** [comment]
We have a proposed logo and banner from Themonera: 

https://www.themonera.art/2019/04/08/proposal-monero-ecosystem-logo/

I personally like this one, but let's see other proposal. @rehrar told me he will come up with an idea as well :)

**Comment by el00ruobuob** [comment]
I like Themonera's logo!

**Comment by erciccione** [comment]
Do we have any other proposed logo? If not i would go for themonera's one.

**Comment by erciccione** [comment]
Opened #29

**Comment by erciccione** [comment]
Logo updated. Take a look at the new readme!

**Comment by erciccione** [comment]
I invite all members of the Ecosystem (@monero-ecosystem/maintainers) to make their membership public (https://github.com/orgs/monero-ecosystem/people). Let's increase the visibility of the project showing off our new logo :)
