### ISSUE TITLE
slow-hash.py

### ISSUE THREAD

**Issue by skftn** [monero-ecosystem/meta#3]
http://www.nothisispatrik.com/2018/03/30/python-reimplementation-of-cryptonights-hash-function/

http://nothisispatrik.com/slow-hash.py

Should be added to the list, however can't find this code on github.

**Comment by erciccione** [comment]
That would be cool to have. i could just create a repo and give credits, but the problem is that it should be kept updated and i'm not able to do that. If somebody can maintain it i will definitely include it

**Comment by skftn** [comment]
You might be able to contact via https://www.reddit.com/user/LarrySDonald

**Comment by erciccione** [comment]
oh great, wasn't able to find any contact on his website, will definitely contact him there. Thanks

**Comment by NoThisIsPatrik** [comment]
Hi. Yeah, I mean to start using github roughly every two-three months (beyond cloning stuff and using it) and it pretty much is always a mess. But you're all correct - it should be in a repo, going to take another stab at it.

**Comment by NoThisIsPatrik** [comment]
There, now it exists. I'm going to try to add some alternate forms besides everything jammed into a single file (I like that is can be, but it's not the most manageable thing ever), but in any case the plain... itself has a repo now.

**Comment by erciccione** [comment]
@NoThisIsPatriyou can transfer the repo now

**Comment by erciccione** [comment]
The 'slow hash' repo is now part of the monero-ecosystem family: https://github.com/monero-ecosystem

**Comment by skftn** [comment]
nice
