### ISSUE TITLE
Add vanity-monero repository

### ISSUE THREAD

**Issue by Equim-chan** [monero-ecosystem/meta#41]
vanity-monero is a CLI tool that generates vanity Monero address.

See https://github.com/Equim-chan/vanity-monero and https://www.reddit.com/r/Monero/comments/8o8wdz/i_just_wrote_a_vanity_address_generator_for_monero/

**Comment by erciccione** [comment]
I approve this project. It doesn't need much maintainance or updates and it's something very cool to have in the Ecosystem. Thak you for proposing it @Equim-chan :)

Let's see what the other members have to say: @monero-ecosystem/maintainers

**Comment by xmrdsc** [comment]
I've used this in the past and it is excellent.

**Comment by lh1008** [comment]
Oh, this is interesting. It would be nice to try it out. There are so many things to learn. Approve :+1:

**Comment by normoes** [comment]
I also very much like the idea. It's like eschalot (onion vanity hostnames) for monero addresses ;)

**Comment by erciccione** [comment]
Looks like we have a clear consensus at the moment. Waiting 24 more hours before labelling as approved and starting the transfer :)

**Comment by erciccione** [comment]
@Equim-chan I sent you an invitation to join the maintainers of the ecosystem, please accept, so that you can start the transfer of the repo. Ping me here when done plase.

**Comment by Equim-chan** [comment]
Transfer is done.

**Comment by erciccione** [comment]
Perfect. Welcome to the Monero Ecosystem Project @Equim-chan. I invite you to add your project to moneroecosystem.org, it will only take some minutes. The repository is [here](https://github.com/monero-ecosystem/monero-ecosystem.github.io).

I'm gonna add the project in meta.

**Comment by erciccione** [comment]
#42 is merged, now we only need to announce the new repo. I will do it later today.

**Comment by erciccione** [comment]
Got caught in other things and didn't have time to do it before, done it now.
Announced [on reddit](https://www.reddit.com/r/Monero/comments/ca5n3c/create_your_personalized_monero_address_with/) and [twitter](https://twitter.com/calciferciccio/status/1147822481731936256)

@Equim-chan I invite you to set your membership in the Ecosystem as public, so to give visibility to the project. You are also welcome to contribute in our consensus mechanism and make suggestions and proposal. Thank you :)
