### ISSUE TITLE
Monero CCS Proposal out for a new project of mine

### ISSUE THREAD

**Issue by omani** [monero-ecosystem/meta#43]
Hi guys,
I would like to bring to your attention my freshly created CCS Proposal for a new project of mine: 

The Monero Tip Bot for Telegram.

Notice the section where I mention the Monero Ecosystem and my plan to put this project under the umbrella of the Monero Ecosystem, like I did recently with my Go Monero RPC Client.

https://repo.getmonero.org/monero-project/ccs-proposals/merge_requests/86

I hope you guys support me in my funding or give me a thumbs up and upvote the proposal.

See you there :)

Cheers!

**Comment by erciccione** [comment]
Thank you for letting us know @omani, especially since the Ecosystem is mentioned. i will comment.

**Comment by dginovker** [comment]
Omani's proposal has successfully been merged - Donation link is up, already 10.80/12.00XMR! https://ccs.getmonero.org/proposals/monero-tip-bot.html

**Comment by erciccione** [comment]
Good to see it moving forward! Please close the issue as there is nothing more we can do about this.

**Comment by omani** [comment]
thank you all for your support!
