### ISSUE TITLE
Monero BIP39 support

### ISSUE THREAD

**Issue by tioann** [monero-ecosystem/meta#44]
Now that Coinomi has provided support for Monero BIP39 derivations, feel free to add the (MIT-licensed, fully open source) repo, in specific the monero branch.
This is a useful tool but it also demonstrates compiling some basic Monero code to webassembly which can be used as a basis for real wallet implementations, not the usual RPC-based stuff.

Repo: https://github.com/Coinomi/bip39
Ready for offline use: https://coinomi.github.io/bip39-monero/

**Comment by erciccione** [comment]
Hi @tioann thanks for opening this issue.

This sounds interesting and i personally wasn't aware of its existence. I have one main concern: the Ecosystem is composed by repositories which are maintained and developed on the Ecosystem. I see the part related to Monero is in a branch of the bip39 repo of the coinomi project. Are you a maintainer of this project? If yes, would you be willing to create a monero-dedicated repository from the 'monero' branch and maintain it on the Ecosystem? (The repository you linked to seems to be coinomi's official one, so in any case i don't think would be possible to transfer the existent repo to the Ecosystem).

I'm labelling this issue as only 'discussion' for now, without starting our governance process, since it's not clear to me yet what you are proposing to add to the Ecosystem (other members of the Ecosystem can change this if they think it's necessary).

**Comment by tioann** [comment]
To make this clear, you are suggesting that a new project is created under the Monero Ecosystem where the code will live and I do the maintenance for it.
This is perfectly acceptable to me and I would be happy to take on the task. Do let me know if there are any other considerations.

**Comment by erciccione** [comment]
> To make this clear, you are suggesting that a new project is created under the Monero Ecosystem where the code will live and I do the maintenance for it.

Yes, this is how the Monero Ecosystem works, please read the readme of this repo for a clear explanation of this project.

Also, it's still not clear to me your role in coinomi's bip39 repo. Could you answer to these concerns?

> Are you a maintainer of this project? If yes, would you be willing to create a monero-dedicated repository from the 'monero' branch and maintain it on the Ecosystem? (The repository you linked to seems to be coinomi's official one, so in any case i don't think would be possible to transfer the existent repo to the Ecosystem).

**Comment by tioann** [comment]
I am, on behalf of Coinomi, the creator of the Monero BIP39 branch. The code is freely available and MIT licensed so creating a repo for this under Monero Ecosystem is not a problem. I am willing to support this code inside the Monero Ecosystem as an individual and I am pleased to do my (small) part in supporting Monero.

**Comment by Lafudoci** [comment]
BIP39 compatible is a nice step for Monero to be integrated in multicoin wallet. I'll happy to see it join ecosystem. But I agree with @erciccione , this tool should be in a dedicate repo. And better to have more customized and precise readme content to avoid confusing. e.g., the online version points to iancoleman.io, but actually it doesn't support Monero yet.

**Comment by erciccione** [comment]
> but actually it doesn't support Monero yet.

@tioann could you give some info about this? i don't see the value in adding the repo if it's not working right now.

**Comment by tioann** [comment]
My understanding was that the Monero Ecosystem project would be the dedicated repo. Maybe you mean the Monero Ecosystem repo to be a fork of an existing one where the Monero BIP39 code is in the master branch?

BIP39 support is definitely useful for multicoin wallets but may also be of use for Monero-only users with Ledger/Trezor devices.

The code is fully functional. Source code (with wasm generation instructions) is in https://github.com/Coinomi/bip39/tree/monero
A "compiled" page (where all js is inlined in the html file, no minimization) suitable for offline use is in https://github.com/Coinomi/bip39-monero/ and directly accessible in https://coinomi.github.io/bip39-monero/?coin=XMR
This last link is what the Coinomi wallet is redirecting to when users choose to export Monero keys.

Let me know what you think.

**Comment by Lafudoci** [comment]
> > but actually it doesn't support Monero yet.
> 
> @tioann could you give some info about this? i don't see the value in adding the repo if it's not working right now.

@erciccione  Sorry, maybe I didn't make it clear. The BIP39 is supported on [coinomi version page](https://coinomi.github.io/bip39-monero/?coin=XMR) which is good work. But the [repo readme](https://github.com/Coinomi/bip39/tree/monero) only shows the [iancoleman version page](https://iancoleman.io/bip39/). So my suggestion was making a up-to-date readme with a dedicated repo for transferring to ecosystem. I assume this way won't be a big problem? @tioann

**Comment by tioann** [comment]
@Lafudoci Indeed, I took very little time updating the README, I just added a preface with a comment without going into details. It seems to be a common pattern with many forks and I guess it helps with rebasing. I will gladly add more info there.

So, do I need to create a repo under my account that will be forked my Monero Ecosystem? I did go through the Ecosystem README but that part is not entirely clear to me.

**Comment by Lafudoci** [comment]
> @Lafudoci Indeed, I took very little time updating the README, I just added a preface with a comment without going into details. It seems to be a common pattern with many forks and I guess it helps with rebasing. I will gladly add more info there.

I could understand, I was just saying the problem should be addressed.

> So, do I need to create a repo under my account that will be forked my Monero Ecosystem? I did go through the Ecosystem README but that part is not entirely clear to me.

Yes, a new repo contain all the thing inside. If it's approved later, the repo owner will be transferred to Monero ecosystem. You'll become ecosystem member as well to maintain the repo.

**Comment by erciccione** [comment]
Sorry i completely misunderstood that statement earlier.

About the repo, yes, as lafudoci says. @tioann You should create a repo in your github profile from the branch "Monero" of the coinomi repo. Then we can vote to transfer it and maintain it on the ecosystem.

> I did go through the Ecosystem README but that part is not entirely clear to me.

Sorry about that. I will check the readme and clarify that point.

**Comment by erciccione** [comment]
@tioann to move forward with this i suggest you to create the repository based on coinomi/bip39 (Monero). So that we can see the repo that would be actually moved to the Ecosystem and we can vote on something "tangible" :).

**Comment by NoThisIsPatrik** [comment]
@tioann Ok, I think I'm missing something here, the coinomi webpage bip39,
monero branch isn't *actually* bip39, right? I presumed it was the "normal"
(for XMR, abnormal anywhere else) bip39-similar-but-not-compliant monero
mnemonic-to-seed thing, but looking back through the discussion, coinomi
(i.e. tioann/you when it comes to the monero branch) it keeps being
referred to as BIP39. That might sound like a very hair-splitting
bureaucratic type of question, but a bunch of the old times have been
arguing back and forth since at least 2016 with some wanting to straighten
things up and become BIP39 compliant, others that there isn't an easy-fix
way to shoehorn the current system into BIP39, and even if it was, it'd
require keeping the legacy code anyhow to restore older wallets. I think
there's agreement that it would have been better to use BIP39 to start with
(now that it's fairly standard, rather than a BTC only thing) to make 3rd
party wallets easier, but also that without also using BIP44 key deviation,
it's not like BIP39 is going to be that crazy much help.

So if it's not BIP39, that might be what people kind of him-haw around
about when talking about it, not feeling sure if perhaps it *is* BIP39, or
who actually gets to say what BIP39 is. I, too, am not entirely sure, I
think XMR is still using that intentionally not-BIP39 thing, but I don't
know enough about it beyond that it's kind of contentious. Either way, if
it "just" a web page implementation of moneros word-to-seed thing, cool,
that might be handy, feel free to include if others agree. If it *is* some
new intergrate-BIP39 scheme, wow, must have missed that, that's huge. And
also, yeah, a web version of that would still be handy..

PL

**Comment by tioann** [comment]
@NoThisIsPatrik you are correct with your nitpicking for BIP39. BIP39 only really supports the original bitcoin curve. The defacto answer to this is to perform the derivation as described in BIP39, perform an extra SHA3 on the result (presumably to reduce any sekp256k1 bias) and finally perform a reduction to a valid ed25519 point (via function sc_reduce32). We use the same scheme in Coinomi and I consider this to be pretty standard now. Also, this is indeed a pretty huge thing but in a benign way, ensuring compatibility across multiwallets.
Let me know if this addresses your concerns.

**Comment by NoThisIsPatrik** [comment]
Indeed it does, thank you. Didn't realize it was a wide enough issue (or
honestly *a* issue beyond monero) to warrant a more general-case solution.
Nicely done.

**Comment by tioann** [comment]
@erciccione I plan on creating the repo this weekend (probably Sunday). Once it is done I will ping you here to move the process further.

**Comment by erciccione** [comment]
@tioann any update?

**Comment by tioann** [comment]
Hey! I have been pretty busy with work and I didn't have the time to work on this. I am going to have the repo ready today.

**Comment by tioann** [comment]
Here is the repo, initial commit. I still need to update the readme to something more reasonable but it is otherwise ready:

https://github.com/Coinomi/bip39-monero

**Comment by erciccione** [comment]
Thank you @tioann. I think we can start with the actual vote.

@monero-ecosystem/maintainers please let know your opinion and feel free to make questions

**Comment by erciccione** [comment]
There are no clear votes yet. Please Ecosystem members make your opinion known.

**Comment by Lafudoci** [comment]
@erciccione The readme still needs to be updated.

**Comment by tioann** [comment]
Agreed, the README will be updated within the next 2 days. I have also been making some changes to the code to avoid conflicts with other webassembly modules which I will be pushing out too.

**Comment by erciccione** [comment]
@tioann any news? :)

**Comment by woodser** [comment]
I support adding BIP39 support for Monero to the ecosystem.  Thanks for your work @tioann.

**Comment by lh1008** [comment]
I support adding Monero BIP39 support. :+1:

**Comment by erciccione** [comment]
We have votes enough to consider this approved. @tioann is the readme up to date?

**Comment by tioann** [comment]
Niiice! The readme is not up to date but I am working on it along with some
small code refactorings. I have been pretty busy with work these days but
things are a bit more quiet so I will be finishing this soon.

**Comment by tioann** [comment]
@erciccione I have just uploaded the latest refactorings to the repo and will be uploading the updated README in the next few hours.

**Comment by erciccione** [comment]
Thank you for the update. I will open the PR to add this project today. Could you take care of adding it to [the website](https://github.com/monero-ecosystem/monero-ecosystem.github.io)?

**Comment by erciccione** [comment]
@tioann i sent you the invitiation to join the Ecosystem, please accept and then transfer the repository please.

**Comment by Lafudoci** [comment]
@erciccione @tioann the README is still iancoleman's none-XMR version. Better to have it done before transfer.

**Comment by tioann** [comment]
I have just uploaded an updated version of the readme.md file, let me know if this works.

**Comment by Lafudoci** [comment]
I just tried it through. The readme is clear and the Monero seed works fine. Good job, I believe it's ready for transferring. @tioann @erciccione

**Comment by erciccione** [comment]
Perfect. Thank you @Lafudoci @tioann 

@tioann you now only need to accept the invitiation and transfer the repo :)

**Comment by tioann** [comment]
I forked the repo under monero-ecosystem, do let me know if all is ok or if I messed up somehow

**Comment by erciccione** [comment]
@tioann the repository must be *trasferred*, not forked. Otherwise we will have 2 repo about the same thing floating around. As it's written in the readme:

> Transfering a repo on the Monero Ecosystem means that the repository will be moved from the personal account, not cloned or mirrored and all development will happen inside the project 'Monero Ecosystem'.

Pleas remove the forked repo and transfer the original one instead :)

**Comment by tioann** [comment]
@erciccione Well, the part "not cloned or mirrored but moved" is a bit of an issue. It was my misunderstanding that I missed it. I could definitely argue for Coinomi to have the repo moved but personally I am not convinced this is the right thing to do for Coinomi. It would be a totally different situation if this was a personal project. So I am at a bit of a loss on what to do here. Maybe moving this to the ecosystem is not the appropriate thing to do. What do you guys think?

**Comment by erciccione** [comment]
@tioann please read carefully the readme of this repository. We could easily fork any repo we would like to have and automatically pull changes from upstream, but that's not what the Ecosystem project is. The point is to build a community of Monero developers and to have a cluster of projects maintained by these developers.

I'm removing the cloned repository, please let us know how would you like to proceed forward. Keep in mind that we only accept transferred repositories. The maintainers still own and maintain their own project.

**Comment by erciccione** [comment]
@tioann Please let us know something soon, otherwise i will just close this issue.

**Comment by erciccione** [comment]
Well, No answer for more than 2 weeks, i'm closing this issue. If some of the maintainers feel this should stay open, please reopen it. You all have the power and right to do so.

To all readers: Before proposing to add a new project, please carefully read the readme of this repository, so we don't waste everybody's time.
