### ISSUE TITLE
Get hard fork date

### ISSUE THREAD

**Issue by normoes** [monero-ecosystem/meta#46]
I have written a script to extract past and future (if available) hard fork dates.

It extracts the dates from `/src/cryptonote_core/blockchain.cpp` in the `monero` repository:
* The repository `branch` can be configured (`master`, `release-v0.14`).
* The `network_mode` can be configured (`mainnet`, `stagenet`, `testnet`).
* The `daemon` can be configured (`node.xmr.to`).
  - This is used to get the block's timestamp (using th method `get_block_header_by_height`).

It's just a script, so I am not sure, whether it makes sense to add it here.
Altogether it's quite useful.

Here you can find the script:

https://github.com/normoes/monero_scripts/blob/master/get_monero_hard_fork_info.py

You can see it in action here (the output is used):

* https://community.xmr.to/xmr-countdown/
* https://community.xmr.to/xmr-countdown/testnet/
* https://community.xmr.to/xmr-countdown/stagenet/

The countdown starts at `0`, because there is no "future" (Version 12) hard fork defined, yet.

This is the output for `mainnet`:
```
Version 1 ['Apr 18 2014 UTC', '1', '1341378000']
Version 2 ['Mar 23 2016 UTC', '1009827', '1442763710']
Version 3 ['Sep 22 2016 UTC', '1141317', '1458558528']
Version 4 ['Jan 10 2017 UTC', '1220516', '1483574400']
Version 5 ['Apr 14 2017 UTC', '1288616', '1489520158']
Version 6 ['Sep 16 2017 UTC', '1400000', '1503046577']
Version 7 ['Apr 06 2018 UTC', '1546000', '1521303150']
Version 8 ['Oct 18 2018 UTC', '1685555', '1535889547']
Version 9 ['Oct 19 2018 UTC', '1686275', '1535889548']
Version 10 ['Mar 09 2019 UTC', '1788000', '1549792439']
Version 11 ['Mar 12 2019 UTC', '1788720', '1550225678']
```

**Comment by erciccione** [comment]
Thank you for proposing this @normoes. I'm not sure if would be a good addition to the Ecosystem. I see its utility, but at the end every hard fork date is posted in the [readme of the Monero repo](https://github.com/monero-project/monero#scheduled-software-upgrades). i see the potential use in those countdown and somebody might find it useful and implement it in their website/service.

I don't know, i'm staying neutral about this for now, let's see what the others have to say @monero-ecosystem/maintainers

**Comment by normoes** [comment]
To be honest, I have the same feelings about it.
I also am neutral :)

**Comment by lh1008** [comment]
Hi, 

Well is kind of a fun script. I remember several times entering to the website to see the hard fork date.

We might find a specific repository for fun projects. Not sure what will happen with RandomX algorithm change, this could then be "lost" forever...(no longer hard forks, that is what I meant, the code will still be there) >:( 

**Inside the church we have a plan to create a universal Monero calendar, trying to build Monero's history. It has not been yet been spoken or organized so not sure what to suggest in this case. We have a repo for the church where this could be added. Just wanted to share with you this

**Comment by normoes** [comment]
@lh1008  Is there a "church" repository somehwere?

**Comment by NoThisIsPatrik** [comment]
Has anyone bumped into actual examples of these ASICs? It's not that I
doubt their existance exactly, but the whole net is full of people
repeating that monero did something to avoid them again. I've seen a few
discussions about fpga, mostly saying that the old CN had a flaw in
calculating next address, which probably referrs to that you can know the
first itteration of each block (using the first bits combined with its
position, which gives you some of the vars from last block, given that it
picked it), and you also briefly hold the "one aes" round for each block as
you chain aes to fill the scratchpad. V2 mostly obfuscates a little. But
neither is much of a "killer", you still need an aes coproc (lots exist),
ram, and some general-purpose flow control and computing. So.. an awful lot
like a small core with cache. People (dunno who, but not fumbling fpga
terms) seem to suggest that's indeed all their fpga pocs are, which doesn't
sound reasonable for asic runs. But I may be way wrong. This guy asked me
some stuff (student) a few months ago which made me re-dig-up a symbolic
bit-by-bit evaluator for keccak and aes i made as a sandbox of sorts, which
reminded me of my earlier hard-won realization - everything but the
explode, implode, and memhard takes constant and very negligible time, and
is only of interest to the degree that it can be partially reversed or
preimaged. (Yes, i need to github that stuff). So it's kind of odd that in
all this debate, no one really points our what "current gen" asics actually
*do*, or how one might discern them from, like, a celeum 96-core armv8, or
a botnet.

Sorry, long post feel free to ignore, waiting rooms and tablets areba
hazardous combo, but I don't want to lose this later, and perhaps it'll
trigger someones knowledge.

**Comment by erciccione** [comment]
We are going a bit off-topic here :). Please let's keep the conversation about only this issue. i encourage to use `#monero-ecosystem` for light or non-focused discussions.

**Comment by NoThisIsPatrik** [comment]
Oh oops, I thought that’s what this was connected to.

**Comment by normoes** [comment]
Sorry no :) This script only parses the file `/src/cryptonote_core/blockchain.cpp` in the `monero/project/monero` repository andextracts the hard fork dates.

**Comment by lh1008** [comment]
@normoes:
https://repo.getmonero.org/churchofmonero
https://github.com/church-of-monero

**Comment by erciccione** [comment]
Some time has passed and seems like there isn' interest in adding this project to the Ecosystem. So, i'm considering it rejected. @normoes please close the issue :)

**Comment by normoes** [comment]
Understood.

**Comment by lh1008** [comment]
@normoes, church's repos are open if you're still interested. Nice day everyone >:).

**Comment by normoes** [comment]
@lh1008 I cannot see any open repositories on gitlab and github.

**Comment by lh1008** [comment]
@normoes I'll be opening one. Do you have any special name in mind of it?

**Comment by normoes** [comment]
@lh1008 Thanks. What about hard_fork_date or hard_fork_scraper? :)
The latter maybe describes the use case better.
