### ISSUE TITLE
Add qml-xmr to the repository

### ISSUE THREAD

**Issue by skftn** [monero-ecosystem/meta#5]
https://github.com/skftn/qml-xmr

Related to GUI wallet development.

**Comment by erciccione** [comment]
Looks like a good addition to me. If it's ok for you i will send you the request to membership so you can transfer the repo

**Comment by erciccione** [comment]
@skftn We can transfer this repo to the monero-ecosystem if you want to, just ping me

**Comment by skftn** [comment]
Thanks!

**Comment by erciccione** [comment]
Repo transferred, the address is: https://github.com/monero-ecosystem/qml-xmr
Thank you!
