### ISSUE TITLE
Add Monero-History-Box, a reskin of the original Candybox idle game, to the Monero Ecosystem!

### ISSUE THREAD

**Issue by dginovker** [monero-ecosystem/meta#51]
I've been working on [Monero-History-Box](https://github.com/dginovker/Monero-History-Box) for some time now, and it's in a fairly playable state. The game is a recreation of [Candybox](https://candybox2.github.io/candybox/), and will hopefully continue expanding with great memes and references to historical components of the Monero community.

It's a little different from most ecosystem projects; it's in a super basic state and really easy for new users to contribute to right now, and has a lot of potential to expand.

Thoughts?

**Comment by erciccione** [comment]
Thank for the proposal @dginovker . Is there a demo of the game online?

@monero-ecosystem/maintainers

**Comment by dginovker** [comment]
Not right now, but I'll post an update when there is.

**Comment by normoes** [comment]
The general idea is great.
Learning by doing in away.

I also would like to see a demo :)

**Comment by dginovker** [comment]
I meant to continue working on this before posting a demo, but since I just haven't actively done so I'll just post the demo here. There's a lot of really cool ideas that can still be done, such as changing the puzzles to be sleek Monero inside jokes, but for now much is still based on the original game: https://monerohistory.github.io

**Comment by Lafudoci** [comment]
Just have played around with the demo. Interesting! I got a iron tier GPU running and overheating LOL. It's a bit weird that purchasing is not by Monero but hashes itself though. IMO it's not ready for transferring yet. I can tell it still needs lots of work. But I'm looking forward to it's potential for sure. It's gonna be fun :)

**Comment by dginovker** [comment]
Thanks for checking it out.

I know it's a bit far out, but I'll definitely be working on this in May. I'll keep you all posted when I finish another good wave of update :).

Closing for now!
