### ISSUE TITLE
GitHub Page to be deployed to the JavaScript project with jsdocs

### ISSUE THREAD

**Issue by woodser** [monero-ecosystem/meta#52]
Just a heads up, a GitHub page containing jsdoc will be deployed to the [monero-javascript](https://github.com/monero-ecosystem/monero-javascript) project over the next few days.  Please let me know if the deployment could interfere with anything.

Perhaps we'd want to reference that documentation somewhere, along with the documentation for the associated [Java](https://moneroecosystem.org/monero-java/) and [C++](https://woodser.github.io/monero-cpp-library/annotated.html) projects?

**Comment by erciccione** [comment]
Thank you for letting us know @woodser, shouldn't interfere iwth anything.

> Perhaps we'd want to reference that documentation somewhere, along with the documentation for the associated Java and C++ projects?

That would be ok i guess, do you have anything particular in mind?

**Comment by erciccione** [comment]
On an unrelated not, but related to monero-javascript. I get a security alert for your repo (`eslint-utils` needs to be updated)

**Comment by erciccione** [comment]
This can be closed.
