### ISSUE TITLE
Create a temporary public repository named OSSRH-51699 in order to verify domain ownership

### ISSUE THREAD

**Issue by woodser** [monero-ecosystem/meta#54]
In order for Bisq to adopt the monero-java project, Bisq developers have requested its artifacts be uploaded to the Maven Central Repository.  Discussion on that here: https://github.com/bisq-network/bisq/pull/3275

I have opened a request to have those artifacts added to the Maven Central Repository: https://issues.sonatype.org/browse/OSSRH-51699

In turn, the hosting provider has requested that we create a public repository named OSSRH-51699 within github.com/monero-ecosystem in order to verify ownership of that project space.

This issue requests a public repository be temporarily created in the monero-ecosystem in order to verify ownership of this project name space.

It appears I am able to create the repository myself, so I will proceed shortly unless there are any objections?

**Comment by erciccione** [comment]
Ok for me.

> It appears I am able to create the repository myself

Just FYI. This is possible because the creation of new repos is activated while we wait for the approved projects to be transferred. Usually it's not possible to add new repositories.

**Comment by woodser** [comment]
Done.
