### ISSUE TITLE
Add: go-xmrto-client repository

### ISSUE THREAD

**Issue by omani** [monero-ecosystem/meta#57]
hi folks,
another repository of mine. A xmr.to client written in go.

https://github.com/omani/go-xmrto-client

feel free to ask questions or give feedback.

cheers!
sun

**Comment by erciccione** [comment]
ping @monero-ecosystem/maintainers

**Comment by Lafudoci** [comment]
I don't know much about GO. But I believe it is an useful tool for Monero ecosystem. Although there is already an demo code, I would suggest to make a table for all functions and their instructions in README, eg. `GetOrderStatus`, `CreateOrder`. So dev could easily find how to use it.

**Comment by normoes** [comment]
I like the idea, itmakeslife easier for "Go people" :)

I have a xmrto python wrapper (client).

Would that be an addition as well?
https://github.com/normoes/xmrto_wrapper

@erciccione What do you think?

**Comment by omani** [comment]
> I don't know much about GO. But I believe it is an useful tool for Monero ecosystem. Although there is already an demo code, I would suggest to make a table for all functions and their instructions in README, eg. `GetOrderStatus`, `CreateOrder`. So dev could easily find how to use it.

@Lafudoci I always put a godoc link in my repos. I just waited with this one to move it to the ecosystem, since the github path will change then. so yeah, documentation will follow.

**Comment by erciccione** [comment]
@normoes feel free to open another issue for that repo, so can be discussed.

I remind that all Ecosystem members can add labels and manage issues in this repo :)

**Comment by rbrunner7** [comment]
Looks ok to me after glancing at it. I don't see any reason not to add this. As code it's not that big but probably still beats writing it myself should I have a need for something like this :)

**Comment by erciccione** [comment]
We have 2 + 1 ACK. We can consider this approved.

@Lafudoci @normoes and especially @rbrunner7 , thanks for voicing your opinion.

**Comment by erciccione** [comment]
@omani you can transfer the repo now. Please comment here when done.

**Comment by omani** [comment]
done.

**Comment by erciccione** [comment]
@omani perfect. Would you take care of adding it to the website? https://github.com/monero-ecosystem/monero-ecosystem.github.io

**Comment by omani** [comment]
> @omani perfect. Would you take care of adding it to the website? https://github.com/monero-ecosystem/monero-ecosystem.github.io

https://github.com/monero-ecosystem/monero-ecosystem.github.io/pull/12

**Comment by Lafudoci** [comment]
> 
> 
> > @omani perfect. Would you take care of adding it to the website? https://github.com/monero-ecosystem/monero-ecosystem.github.io
> 
> [monero-ecosystem/monero-ecosystem.github.io#12](https://github.com/monero-ecosystem/monero-ecosystem.github.io/pull/12)

Great job, merged. @omani @erciccione

**Comment by erciccione** [comment]
Announced on reddit (https://www.reddit.com/r/Monero/comments/ds191t/2_new_projects_join_the_monero_ecosystem_the/) and Twitter (https://twitter.com/calciferciccio/status/1191749090981359620)

**Comment by erciccione** [comment]
Thanks everybody for participating to the discussion and for voting :)
