### ISSUE TITLE
Add monero-cpp-library to the ecosystem?

### ISSUE THREAD

**Issue by woodser** [monero-ecosystem/meta#58]
Hi, I am wondering if it makes sense to add my project, [monero-cpp-library](https://github.com/woodser/monero-cpp-library), to the monero-ecosystem?

`monero-cpp-library` is a C++ version of [monero-java](https://github.com/monero-ecosystem/monero-java) and [monero-javascript](https://github.com/monero-ecosystem/monero-javascript).  It provides a C++ library for using a Monero wallet by wrapping Monero Core's C++ wallet, [wallet2](https://github.com/monero-project/monero/blob/master/src/wallet/wallet2.h).

`monero-cpp-library` conforms to the same [API specification](http://moneroecosystem.org/monero-java/monero-spec.pdf) used in `monero-java` and `monero-javascript`.  It is used by `monero-java` to provide a full wallet in Java using JNI native binding to Monero Core.

It is my hope that this library may form the basis of adding a new wallet interface to monero-project long term for the wallet RPC server, GUI, and application developers to build on top of.

Thoughts?

**Comment by erciccione** [comment]
ping @monero-ecosystem/maintainers

**Comment by woodser** [comment]
@normoes monero-wallet-cli is a terminal application which uses monero-project's wallet2 in order to provide a wallet application in the terminal, whereas this is a software library which wraps wallet2 in order to provide a more robust and general-purpose wallet interface for applications like monero-wallet-cli to use.

wallet2 was not designed to be a general-purpose wallet interface and can be difficult to use, so it is my hope that monero-project adopts an interface like this for monero-wallet-cli, monero-wallet-rpc, the GUI, and external application developers to build on long term.

**Comment by normoes** [comment]
Now I get it. Sounds good to me.

**Comment by erciccione** [comment]
@woodser are you still interested in moving this to the Ecosystem?

**Comment by woodser** [comment]
Sure.

**Comment by woodser** [comment]
Do you still want this moved to the ecosystem?  I'm about to release v0.3.0 of all three libraries (Java, JavaScript, and C++), so now is probably a good time to do it.

**Comment by erciccione** [comment]
@woodser Sure, but i would like to have some more ACKs first. At the moment only @normoes commented.

**Comment by Lafudoci** [comment]
@erciccione  I thought is the same with @normoes , the more implementation for wallet dev is always better. But I'm not good at C++ either. So I would say it's nice to add it but unable to give a technical review.

**Comment by erciccione** [comment]
I don't think a strict technical review is necessary in this case. Woodser is a known and respected member of this community, i think his other works speak for his competence. IMO we can consider this accepted.

**Comment by woodser** [comment]
I'm getting "You don’t have the permission to create public repositories on monero-ecosystem" when I try to transfer the repository.

**Comment by erciccione** [comment]
@woodser Try again pls

**Comment by woodser** [comment]
Thanks.  It's transferred now.  But I'm not able to edit the description and website.

**Comment by erciccione** [comment]
When a repo is added to a github project, for some reason the permissions of the maintainer change to "read" instead of "admin". I usually manually change it to "admin" after a repo is added. It's fixed now.

**Comment by erciccione** [comment]
Added in #69. Somebody please review :)

**Comment by erciccione** [comment]
https://github.com/monero-ecosystem/monero-ecosystem.github.io/pull/18

**Comment by xmrdsc** [comment]
Glad to see this get added!

**Comment by erciccione** [comment]
Announced on Reddit and Twitter

https://www.reddit.com/r/Monero/comments/gnvdmz/a_new_project_joins_the_monero_ecosystem/

https://twitter.com/calciferciccio/status/1309776922994450432

**Comment by erciccione** [comment]
Thanks everybody for the discussion and for voting :)
