### ISSUE TITLE
Add: xmrto_wrapper in python

### ISSUE THREAD

**Issue by normoes** [monero-ecosystem/meta#59]
Hi,

I have written a python wrapper for XMR.to:
https://github.com/normoes/xmrto_wrapper

You can create orders, track orders and get the recent prices.

It can be used as module and as script and can be installed using pip - Not yet on PyPi, though.

I find that very useful, especially from a developer's point of view. I wouldn't have created it otherwise :)

**Comment by Lafudoci** [comment]
It looks good, should be very useful for Monero python dev. I vote `ack`.

**Comment by erciccione** [comment]
Ping @monero-ecosystem/maintainers

**Comment by erciccione** [comment]
Any other opinion on this? @monero-ecosystem/maintainers

**Comment by omani** [comment]
ack.

**Comment by emesik** [comment]
Looks good

**Comment by erciccione** [comment]
Thank you for voting everybody. 3ACK, We can consider it approved :).

@normoes Please ping me here or in one of the chats to start the transfer.

**Comment by normoes** [comment]
@erciccione Ready.

**Comment by erciccione** [comment]
@normoes ready for the transfer. Ping me here when done please.

**Comment by normoes** [comment]
@erciccione Transferred. :+1:

**Comment by erciccione** [comment]
@normoes Could you add the project to the website? https://github.com/monero-ecosystem/monero-ecosystem.github.io

Otherwise i or somebody else will add it for you, but that will delay things further more.

**Comment by normoes** [comment]
@erciccione 
I created this [PR](https://github.com/monero-ecosystem/monero-ecosystem.github.io/pull/14).

**Comment by erciccione** [comment]
Announced on Twitter: https://twitter.com/calciferciccio/status/1221042077640863746 and reddit: https://www.reddit.com/r/Monero/comments/etq0wh/a_new_project_joins_the_monero_ecosystem_xmrto/

Better late than never, no? :P

**Comment by normoes** [comment]
Wohoo ;)
