### ISSUE TITLE
Add Lunlumo to the repository

### ISSUE THREAD

**Issue by Leza89** [monero-ecosystem/meta#6]
To my shame I have to admit that I haven't tried it myself yet; Anyway:

https://github.com/nasaWelder/lunlumo

**Comment by erciccione** [comment]
what @nasaWelder thinks about this? would you transfer the repo to the monero-ecosystem? 
Also, do you plan to regularly update it?

**Comment by erciccione** [comment]
Contacted him on reddit and pigned here. No answer. I take it as a 'no'.
Closing this

**Comment by nasaWelder** [comment]
hi @erciccione @Leza89 I got a new phone and didn't re-install these apps... sorry about that
