### ISSUE TITLE
Add: Real-time authorizations and DAPI via Supernode layer

### ISSUE THREAD

**Issue by dinpd** [monero-ecosystem/meta#60]
https://github.com/graft-project/graft-ng

PoS based Supernode layer for Monero.  Real-time authorizations and DAPI.  

We have completed the DHT based communication, Authorization quorum selection, Blockchain based list based disqualifications.

Checking on the interest in Monero ecosystem community to take on and maintain what we've developed.

**Comment by erciccione** [comment]
Hi @dinpd thanks for proposing thus project.

> Checking on the interest in Monero ecosystem community to take on and maintain what we've developed.

what do you mean? Are you looking for somebody willing to maintain *graft-ng* or you want to transfer the project to the Ecosystem and maintain it yourself?

**Comment by dinpd** [comment]
Mostly the former, but we could pitch in as well.

**Comment by erciccione** [comment]
I just realized that this is Graft. I didn't know the maintainers intended to not work on it anymore? Could you share the reason? IIRC  the project was advertised on reddit not long ago.

**Comment by dinpd** [comment]
Limited resources.  We’re still chopping away at it, just not as fast as we’d like.   Figuring that with extra help it can be done much faster.
