### ISSUE TITLE
Add: telegram-monerotipbot

### ISSUE THREAD

**Issue by omani** [monero-ecosystem/meta#62]
hi folks,
here it is finally. the Telegram Monero Tip Bot from the CCS proposal https://ccs.getmonero.org/proposals/monero-tip-bot.html

https://github.com/omani/telegram-monerotipbot

happy tipping! :)

**Comment by erciccione** [comment]
Ping @monero-ecosystem/maintainers

**Comment by lh1008** [comment]
Amazing. :+1:

**Comment by Lafudoci** [comment]
Great work. `ACK`

**Comment by normoes** [comment]
Nice.

**Comment by erciccione** [comment]
I `ACK` only at the condition that https://github.com/omani/telegram-monerotipbot/issues/1 is resolved first. Calling a custodial wallet "Official", beside being uncorrect, is extremely dangerous and could lead of sever problems in the future.

**Comment by omani** [comment]
@erciccione thank you for reminding me of that potentially dangerous act.

I resolved your issue.

**Comment by erciccione** [comment]
A clear approval. Thanks everybody for voting :)

@omani you can transfer the repo now. Please comment here when it's done.

**Comment by omani** [comment]
> A clear approval. Thanks everybody for voting :)
> 
> @omani you can transfer the repo now. Please comment here when it's done.

welcome the telegram-monerotipbot to its new home:
https://github.com/monero-ecosystem/telegram-monerotipbot

PR for website:
https://github.com/monero-ecosystem/monero-ecosystem.github.io/pull/13

**Comment by erciccione** [comment]
Please review #64

**Comment by omani** [comment]
> Please review #64

done

**Comment by erciccione** [comment]
I've been travelling and with a coming and going internet connection. I will make the annuncement on reddit tomorrow (hopefully).

**Comment by erciccione** [comment]
Announced on reddit (https://www.reddit.com/r/Monero/comments/ds191t/2_new_projects_join_the_monero_ecosystem_the/) and Twitter (https://twitter.com/calciferciccio/status/1191749090981359620)

**Comment by erciccione** [comment]
Thanks everybody for voting! The bot is transferred and announced :)
