### ISSUE TITLE
Add Monero Outreach repository

### ISSUE THREAD

**Issue by lh1008** [monero-ecosystem/meta#7]
Monero Outreach is working on educational material for the community. The Contribute repository is where all the documentation will be forward for translations.

https://github.com/monero-outreach/Contribute 

:)

Thank you.

**Comment by erciccione** [comment]
Happy to welcome the Monero Outreach repo, but as you said in monero-outreach/Contribute#4 , we need a better name for that repo before transferring it to the monero-ecosystem. Let me know when that is done, so we can start the transfer

**Comment by lh1008** [comment]
Sure thank you @erciccione ! :smile:

**Comment by lh1008** [comment]
Hi @erciccione 

The repository's name has been changed. [Issue closed](https://github.com/monero-outreach/outreach-docs/issues/4)

This is the new repository's name:

https://github.com/monero-outreach/outreach-docs.git

**Comment by erciccione** [comment]
ping @lh1008

**Comment by lh1008** [comment]
@erciccione I sent a message two days ago through mattermost. I'll be sending another message. :)

**Comment by erciccione** [comment]
Transfer completed: https://github.com/monero-ecosystem/outreach-docs
