### ISSUE TITLE
Add: python monero health checker module

### ISSUE THREAD

**Issue by normoes** [monero-ecosystem/meta#70]
I would like to introduce `monero_health` to you. It is written in python and is a module to return health or status information about `monerod`.

https://github.com/normoes/monero_health

The README describes its usage and responses.

This module is used on the XMR.to community hub - The module provides the running serice with the JSON result.
* https://community.xmr.to/node/mainnet/health/api/v1
* https://community.xmr.to/node/mainnet/health/api/v1/health
* https://community.xmr.to/node/mainnet/health/api/v1/monerod
* https://community.xmr.to/node/mainnet/health/api/v1/monerod/health
* https://community.xmr.to/node/mainnet/health/api/v1/last_block
* https://community.xmr.to/node/mainnet/health/api/v1/last_block/health

The idea is to make the monero daemon status available in a readable format, right now only JSON.

Definition of status (see [README](https://github.com/normoes/monero_health)):
* There are the P2P and the RPC status - This is essentially about connectivity + information like the hardfork version. Both are combined in the status found at `/monerod/health`.
* There is the `last_block` status, which defines an age limit (`12 [minutes]`) of a block and returns `OK` if the block is younger than that or `ERROR` if the block is older than that.

What do you think?

**Comment by Lafudoci** [comment]
This is good. A nice python module which could be easily integrated. Remote node health is important for Monero service project. I vote `ACK`.

**Comment by erciccione** [comment]
Cool project. `ACK` for me as well, but @normoes could you add a license? I think it's important that for the nature of the Ecosystem project itself, all projects should be licensed, to not make contribution/distribution hard.

**Comment by normoes** [comment]
Good point. `LICENSE` added.

**Comment by erciccione** [comment]
@monero-ecosystem/maintainers any opinion/vote about this?

**Comment by emesik** [comment]
`ACK` from me, definitely. This seems very useful, especially when `monerod` is not a super reliable piece of software.

**Comment by erciccione** [comment]
Thank you for voting. We can consider this accepted. @normoes you may start the transfer whenever you are ready. Please ping me when it's done :)

**Comment by normoes** [comment]
I finished transferring the repository:
* https://github.com/monero-ecosystem/monero_health
* https://pypi.org/project/monero-health/

**Comment by erciccione** [comment]
Added to the README with #73
