### ISSUE TITLE
Add: python monero scripts

### ISSUE THREAD

**Issue by normoes** [monero-ecosystem/meta#71]
The python module `monero_scripts` can be found here:
* https://github.com/normoes/monero_scripts
* https://pypi.org/project/monero-scripts/

It is more or less a collection of scripts in order to tackle the 3 (at the moment) following use cases:
* Get the hard fork dates from `github/monero-project` from within `src/hardforks/hardforks.cpp`.
* Get the seed nodes from `github/monero-project` from within `src/p2p/net_node.inl`.
* Check the P2P connectivity.

`monero_scripts` is used on the XMR.to community hub to provide hard fork and seed node status information:
* https://community.xmr.to/xmr-countdown/
* https://community.xmr.to/xmr-seed-nodes

**Comment by erciccione** [comment]
Thanks for the proposal.

How are this script related with the health checker proposed in #70?

ping @monero-ecosystem/maintainers for voting.

**Comment by normoes** [comment]
[`monero_health`](https://github.com/monero-ecosystem/meta/issues/70) makes use of the 3rd use case that `monero_scripts` provides, i.e. checking the daemon's accessibility on its P2P port.

Everything else that comes with `monero_health` is with regard to daemon status information and unrelated to `monero_scripts`.

**Comment by emesik** [comment]
Sure, I'll `ACK` it. However, this stuff might as well become a part of the general Python module.

**Comment by Lafudoci** [comment]
I agree with @emesik . It will be very nice to see it becomes a part of Python Monero module. But it's still good work for adding to ecosystem in current form since it's already well packaged and documented. I vote ACK.

**Comment by erciccione** [comment]
Thank you for voting. We can consider this accepted. @normoes you may start the transfer whenever you are ready. Please ping me when it's done :)

**Comment by erciccione** [comment]
@normoes any news about the transfers?

**Comment by normoes** [comment]
Today is the day :+1: 

Thanks for the reminder.

**Comment by normoes** [comment]
I finished the first package:
* https://github.com/monero-ecosystem/monero_health
* https://pypi.org/project/monero-health/

**Comment by normoes** [comment]
I finished transferring the repository:
* https://github.com/monero-ecosystem/monero_scripts
* https://pypi.org/project/monero-scripts/

**Comment by erciccione** [comment]
Nice :)

Better keep this open until we went through all the steps for new repositories. Same for #70.

**Comment by erciccione** [comment]
Added to the README with #73

**Comment by erciccione** [comment]
To officialize this, it needs to be added to the website repo: https://github.com/monero-ecosystem/monero-ecosystem.github.io

**Comment by normoes** [comment]
I can do that.

**Comment by normoes** [comment]
By the way, the tools (in action) can be found here nowadays:
* https:///melo.tools/xmr-countdown
* https:///melo.tools/xmr-seed-nodes

**Comment by normoes** [comment]
Could someone please take a look at the pull  request:
* https://github.com/monero-ecosystem/monero-ecosystem.github.io/pull/24

There is not much that can be done wrong but there is a chance ;)

@erciccione

**Comment by erciccione** [comment]
Reviewed. Thanks @normoes, let's wait for @Lafudoci's review now :)

**Comment by Lafudoci** [comment]
Good job @normoes , and thanks @erciccione. It has been merged.
