### ISSUE TITLE
Adding C# Monero RPC Client to Ecosystem

### ISSUE THREAD

**Issue by Agorist-Action** [monero-ecosystem/meta#72]
Hey,

Can we add this project to the Monero Ecosystem? Rbrunner7 has reviewed it. Thanks

https://github.com/Agorist-Action/csharp-monero-rpc-client

**Comment by erciccione** [comment]
Hi @Agorist-Action thanks for the proposal :)

ping @monero-ecosystem/maintainers for voting.

@rbrunner7 [comment on reddit](https://www.reddit.com/r/Monero/comments/juejr7/c_monero_daemon_and_wallet_rpc_client_now/gcedl1y/)

**Comment by Agorist-Action** [comment]
How many people need to vote? Haha, looks like they're on vacation.

**Comment by emesik** [comment]
You may generally count me as voting for adding every Monero-related project that is not malicious. No matter how advanced they are, it's good to keep them in one place, as long as authors are able to move away should they decide it's better.

Any developer looking for libs would be then directed to monero-ecosystem with a remark that we do not guarantee anything, just like FLOSS never did.

Anyway, count me in.

**Comment by normoes** [comment]
Me too. This is a very good addition.

**Comment by erciccione** [comment]
> You may generally count me as voting for adding every Monero-related project that is not malicious.

@emesik i see your point, but let's keep in mind this is not just a collection of the repositories. The initial aim of the Monero Ecosystem project is to create a loose community of developers working on up-to-date and high quality tools. Who becomes part of the "community" will also have voting rights.

> as long as authors are able to move away

The repos are always owned by the author, so yeah, people can move out whenever they like.

@emesik @normoes thank you both. Let's see if somebody else wants to vote.

**Comment by Agorist-Action** [comment]
Can we directly tag people who haven't voted but whose opinion you'd like? Not sure if someone will vote if they haven't done so in a week.

**Comment by erciccione** [comment]
@Agorist-Action There is no rush, people might be busy and take their time to review. We also have 2 repositories in the process of being added, better wait until those are added first IMO.

**Comment by Lafudoci** [comment]
I am not a C# dev so I did not review the code. But new implementations are important seeds for the ecosystem. Therefore I vote yes for this proposal.

**Comment by Agorist-Action** [comment]
I think this should be added under Libraries and Helpers [here](https://web.getmonero.org/resources/developer-guides/), post approval.

**Comment by erciccione** [comment]
I think we can safely consider this approved :) Thanks everybody for voting.

@Agorist-Action you can transfer the repository any time. Please let me know when the transfer is completed.

**Comment by erciccione** [comment]
> I think this should be added under Libraries and Helpers here, post approval.

Good idea: https://github.com/monero-project/monero-site/issues/1375

**Comment by Agorist-Action** [comment]
@erciccione Transfer it to you? And what happens if you get hacked?

**Comment by erciccione** [comment]
Did you read about the Monero Ecosystem before proposing to add your project? Please read the README of this repository.

**Comment by erciccione** [comment]
> Transfer it to you or to monero-ecosystem?

To monero-ecosystem.

> Can the repository be deleted if monero-ecosysten and/or yourself are hacked?

You can delete a repository any time. You should just let us know if you do that.

> Can this repository remain private in my control while also appearing on the Monero website as described here monero-project/monero-site#1375 ?

Sure, but then why did you propose to add it to the Monero Ecosystem?

**Comment by Agorist-Action** [comment]
No I didn't previously read it. I read it just now. Thanks for answering my questions.

**Comment by Agorist-Action** [comment]
I tried to transfer and get this: You don’t have the permission to create public repositories on monero-ecosystem

**Comment by erciccione** [comment]
i forgot to send you the invitation. After you accepted that you'll be able to start the transfer.

**Comment by Agorist-Action** [comment]
Transfered

**Comment by erciccione** [comment]
Adding with #74

**Comment by Agorist-Action** [comment]
Thanks for the update!

**Comment by Agorist-Action** [comment]
Ill let you know when I'm ready for an announcement about this repository. I'm working on this PR which is reconciling the APIs in the documentation with that of the actual source code: https://github.com/monero-ecosystem/csharp-monero-rpc-client/pull/16

@erciccione

**Comment by erciccione** [comment]
> Ill let you know when I'm ready for an announcement about this repository.

Thanks. If you prefer to make the announcement yourself, please do so! :)

**Comment by Agorist-Action** [comment]
I don't have a Reddit account, or an account on any social media. I've authored a post for you, if you'd be able to make the post for me. It should be made in conjunction with the addition of this repository to Monero's official website (with this [PR](https://github.com/monero-project/monero-site/issues/1375))

> We're glad to announce the addition of a C# library to interface with Monero. This library interacts with Monero's JSON-RPC, allowing for seamless programmatic access to both the daemon and wallet, and is built on .netstandard2.1. We welcome all C# developers in the community to use the library in their C# applications as they build Monero-interfacing applications. The latest version of the library is available on Nuget [here](https://www.nuget.org/packages/Monero.Client/), with the Github link available both on the Monero official [website ](https://web.getmonero.org/resources/developer-guides/) and on the Monero Ecosystem's official Github [repository](https://github.com/monero-ecosystem/csharp-monero-rpc-client).

**Comment by erciccione** [comment]
I opened https://github.com/monero-project/monero-site/pull/1403 to add csharp-monero to getmonero. Still needs to be added to https://github.com/monero-ecosystem/monero-ecosystem.github.io

**Comment by Agorist-Action** [comment]
> All the project belong to the Monero Ecosystem could add a project post on the page.

Ah, okay. I will do this later today.

**Comment by Agorist-Action** [comment]
Can my Markdown section simply link to Github Documentation? I may add a Wiki to my projects repository.

**Comment by Lafudoci** [comment]
> Can my Markdown section simply link to Github Documentation? I may add a Wiki to my projects repository so I can keep all documentation in one place.

Sure, you only have to fill out all the meta: title, description, tags ... etc. Rest of the markdown content is up to you.

**Comment by Agorist-Action** [comment]
@Lafudoci https://github.com/monero-ecosystem/monero-ecosystem.github.io/pull/19

**Comment by Agorist-Action** [comment]
Awesome, it is on the website now: https://www.getmonero.org/resources/developer-guides/

Happy to be part of this community.

**Comment by Agorist-Action** [comment]
Made a Reddit post: https://www.reddit.com/r/Monero/comments/kysiq8/c_monero_library_joins_the_monero_ecosystem_and/

Awaiting erciccione's Twitter post when his time is free.

**Comment by erciccione** [comment]
I posted it on Twitter fwiw: https://twitter.com/calciferciccio/status/1350728829627752448

Thanks for making the reddit post :)

**Comment by erciccione** [comment]
Transfer completed! Thanks everybody :)
