### ISSUE TITLE
add docker-monero-node?

### ISSUE THREAD

**Issue by Gingeropolous** [monero-ecosystem/meta#75]
https://github.com/lalanza808/docker-monero-node

?

**Comment by erciccione** [comment]
Thanks for proposing these, but let's see if the maintainer (@lalanza808) agree with the transfer first, then we can discuss each project in their own issue :)

**Comment by lalanza808** [comment]
I'm open to doing so. Thanks for the heads up @Gingeropolous 😄

**Comment by erciccione** [comment]
Edited title and description and opened #76, so each repository can be discussed and voted. @monero-ecosystem/maintainers

**Comment by Lafudoci** [comment]
Very good work @lalanza808. I vote yes.
