### ISSUE TITLE
Add xmr-node-cannon-do

### ISSUE THREAD

**Issue by erciccione** [monero-ecosystem/meta#76]
https://github.com/lalanza808/xmr-node-cannon-do

As initially suggested in #75

ping @lalanza808

**Comment by erciccione** [comment]
See https://github.com/monero-ecosystem/meta/issues/75#issuecomment-805532646

ping @monero-ecosystem/maintainers

**Comment by Lafudoci** [comment]
Interesting project. A pay-as-you-go Monero node. I vote yes.
