### ISSUE TITLE
add Monero Debian Package

### ISSUE THREAD

**Issue by adrelanos** [monero-ecosystem/meta#77]
https://gitlab.com/whonix/monero-gui

**Comment by erciccione** [comment]
Thanks for proposing to migrate this very important project. Please make sure to read the ['Join the ecosystem'](https://github.com/monero-ecosystem/meta#join-the-ecosystem) section of the README.

**Comment by erciccione** [comment]
ping @monero-ecosystem/maintainers for opinions and votes.

**Comment by Lafudoci** [comment]
Absolutely yes. No doubt the package improves the user experience of Monero project.
