### ISSUE TITLE
Add Moneriote-python (collect opennode for public service)

### ISSUE THREAD

**Issue by Lafudoci** [monero-ecosystem/meta#8]
I have worked on this repo for months. And I think it's stable enough for adding into ecosystem.
https://github.com/Lafudoci/moneriote-python

This scripts to maintain Monero opennodes DNS records. I have run one for months, and it's already listed on MoneroWorld 18089 opennode (opennode.xmr-tw.org:18089).

So basically I'll continually maintain this script for sure and there are something I'm planing to improve on it:

- Ability to add more reference nodes for stable height determination.
- Subdomains (us, eu, asia) point records by IP's location for better user experience.

**Comment by erciccione** [comment]
Ok for me. let's see if anybody from @monero-ecosystem/maintainers has something to say about it. if not, we can start the transfer

**Comment by skftn** [comment]
I’d like to improve code quality. Do you mind a PR @Lafudoci ?

**Comment by Lafudoci** [comment]
@skftn No problem! My python skill is self-learning. So any coding suggestion or revision is appreciated.

**Comment by lh1008** [comment]
I'm not a python expert so I can't really say something about the code but is good to have initiatives by contributors for the Monero Ecosystem. :]

**Comment by skftn** [comment]
@Lafudoci Ok I'm currently rewriting lots of code (hope you dont mind ^^), I have some questions: https://github.com/Lafudoci/moneriote-python/issues/1

**Comment by Lafudoci** [comment]
@skftn No, it's totally fine. Large part of the code were also adopted from previous monero contributor  Gingeropolous and connorw600. So it's nice to have these work step foreword.

**Comment by skftn** [comment]
See https://github.com/Lafudoci/moneriote-python/pull/2

**Comment by Lafudoci** [comment]
@erciccione Lafudoci/moneriote-python#2 got merged. Could we start to transfer?

**Comment by erciccione** [comment]
Transfer concluded. Closing this issue
