### ISSUE TITLE
Add Nim Monero Client to Ecosystem

### ISSUE THREAD

**Issue by eversinc33** [monero-ecosystem/meta#80]
Hey,

I was missing monero-RPC bindings in Nim for a private project, so I created them myself. I then got referred to this github org for my below repository and would like to add it to the monero-ecosystem:

https://github.com/eversinc33/nim-monero-rpc

I plan on adding monero node RPC as well, but I am not yet familiar enough with the usage. Also want to add it to the nimble package list, if it gets incorporated into the monero-ecosystem, so Nim developers can add monero RPC support simply by adding `monerorpc` to their nimble-file. EDIT: both is done now

Let me know what you think.

**Comment by eversinc33** [comment]
@erciccione Is the monero ecosystem still maintained? I see the last merged PR was in 2020

**Comment by eversinc33** [comment]
Great to hear. I understand how this can be time consuming. I would still love to have my library integrated into the ecosystem organisation. Plus, I'd be glad to get involved and help with maintaining it.

**Comment by erciccione** [comment]
Sounds good @eversinc33. Let me ping the other members :) @monero-ecosystem/maintainers

**Comment by Lafudoci** [comment]
Thank you @erciccione.  TBH, I don't know much about Nim. But I believe more RPC client implementations are always good for Monero ecosystem. So I vote yes. Good job @eversinc33.
