### ISSUE TITLE
Add monero-helm

### ISSUE THREAD

**Issue by plowsof** [monero-ecosystem/meta#82]
*note - the text below is from user https://github.com/vdo . Are they banned for some reason here? (they are unable to make issues)

----
Based on a previous docker based project (xmr.sh) I decided to work on a helm package for Monero. Using docker-compose becomes complex and inconvenient fast.

Helm is a state-of-art, template based package manager to install stuff on Kubernetes. Since Monero is usually run on single node machines, there hasn't been a huge need for it yet. However, for production deployments on cloud, or even for domestic deployments with hobby k8s clusters, having a Helm package is a must. You can also leverage the devops tooling available for k8s, which is extensive, and it can still be run on single machines with a lightweight distribution like K3s.

Before publishing this to a public repository like https://artifacthub.io I think this deserves to be under the umbrella of the community here.

There's still some features I want to add ASAP before publishing, but I'm creating this ticket to start the conversation about it. Some of the features are:

* Network selection
* Prometheus exporter (optional)
* Block explorer container (optional)
* LWS (optional)

I tried this Helm chart both on AWS EKS cloud managed cluster, and on a k3s deployment on a Raspberry Pi, and it's already functional. I can provide example `values.yaml` files for both, eventually.

https://github.com/vdo/monero-helm    

---

**Comment by vdo** [comment]
Thanks @plowsof 

For some reason I can't create issues here (but I can on other repos), but I confirm the text above is mine.
